#!/usr/bin/env python3
"""
Populates the 'tracks' table in database/gt_academy.db with all 41 Gran Turismo 6
circuit locations. Includes deep development history, laser scan data, real-world
motorsport heritage, driving tips, and curious facts.
"""
import os
import sys
import json
import sqlite3

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB_PATH = os.path.join(BASE_DIR, 'database', 'gt_academy.db')

TRACKS_DATA = [
    # ==========================================
    # 1. CIRCUITOS REALES DEL MUNDO
    # ==========================================
    {
        "name": "Silverstone Circuit",
        "slug": "silverstone",
        "category": "Real",
        "country": "Reino Unido",
        "country_code": "uk",
        "location": "Northamptonshire, Inglaterra",
        "length_km": 5.89,
        "turns": 18,
        "elevation_m": 11.3,
        "longest_straight_m": 770.0,
        "layouts_count": 5,
        "time_progression": 1,
        "weather_change": 1,
        "laser_scanned": 1,
        "first_game": "Gran Turismo 6",
        "record_lap": "1:27.097 (Max Verstappen, Red Bull RB16, 2020)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/7/7c/Silverstone_Circuit.jpg/revision/latest/scale-to-width-down/600?cb=20161125131323",
        "svg_path": "assets/tracks/silverstone.svg",
        "history_gt": "Silverstone es el hogar espiritual del programa Nissan PlayStation GT Academy. Para Gran Turismo 6, Polyphony Digital desplegó por primera vez en este trazado camiones de escaneo láser 3D de alta densidad (LiDAR), capturando cada bache, rugosidad del asfalto y gradiente de peralte con una resolución inferior a 1 centímetro. Yamauchi y su equipo grabaron además la variabilidad meteorológica británica en tiempo real, modelando la acumulación dinámica de charcos en las enlazadas de Maggotts y Becketts.",
        "history_real": "Construido sobre una base aérea de bombarderos de la Segunda Guerra Mundial de la RAF (Royal Air Force) en 1943, Silverstone albergó el 13 de mayo de 1950 la primera carrera de la historia del Campeonato Mundial de Fórmula 1, ganada por Giuseppe Farina con Alfa Romeo. Es el epicentro del automovilismo británico donde tienen su sede 7 de las 10 escuderías de F1 en el 'Motorsport Valley'.",
        "driving_tips": "El complejo Maggotts-Becketts-Chapel exige máxima precisión aerodinámica y una transferencia de pesos milimétrica: no toques los frenos bruscamente, usa una pequeña retención de acelerador para clavar el morro. La frenada en Stowe (al final de la recta Hangar Straight) requiere retrasar el vértice para traccionar fuerte hacia Vale y Club.",
        "curiosities": [
            "Las tres pistas de despegue originales de la base aérea de la RAF todavía forman la silueta interna del circuito triangular.",
            "En GT6, Silverstone incluye cuatro variantes oficiales: Grand Prix Circuit, International Circuit, National Circuit y Stowe Circuit.",
            "Fue en este asfalto donde Lucas Ordóñez y Jann Mardenborough pasaron de jugadores de PlayStation a pilotos profesionales de las 24 Horas de Le Mans."
        ]
    },
    {
        "name": "Mount Panorama Motor Racing Circuit (Bathurst)",
        "slug": "mount-panorama",
        "category": "Real",
        "country": "Australia",
        "country_code": "pdi",
        "location": "Bathurst, Nueva Gales del Sur",
        "length_km": 6.21,
        "turns": 23,
        "elevation_m": 174.0,
        "longest_straight_m": 1916.0,
        "layouts_count": 1,
        "time_progression": 1,
        "weather_change": 1,
        "laser_scanned": 1,
        "first_game": "Gran Turismo 6",
        "record_lap": "1:59.291 (Christopher Mies, Audi R8 LMS Ultra, 2018)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/3/30/Mount_Panorama.jpg/revision/latest?cb=20171220082432",
        "svg_path": "assets/tracks/mount_panorama.svg",
        "history_gt": "Debut estelar absoluto en Gran Turismo 6 tras años de peticiones de los fanáticos oceánicos. Polyphony Digital realizó un exhaustivo escaneo láser topográfico del monte Wahluu con una elevación vertical de 174 metros entre el pit lane y la cima de Skyline. En GT6, Bathurst cuenta con ciclo horario dinámico completo: los jugadores pueden comenzar la carrera en la oscuridad previa al amanecer y ver salir el sol sobre las llanuras australianas reflejado en el parabrisas.",
        "history_real": "Inaugurado en 1938 como carretera pública panorámica, Mount Panorama es un circuito no permanente que todavía funciona como vía pública con límite de 60 km/h cuando no hay carreras. Es la catedral del automovilismo australiano y sede de las legendarias 1000 Millas de Bathurst (Supercars) y las 12 Horas de Bathurst de GT3. Peter Brock ('El Rey de la Montaña') ganó aquí 9 veces.",
        "driving_tips": "El sector de montaña (The Cutting, Reid Park, Sulman Park, Skyline y The Dipper) es claustrofóbico y no permite ningún error: los muros de hormigón están pegados a las ruedas. En 'The Dipper', el coche pierde casi todo el apoyo vertical en un desnivel violento hacia la izquierda; mantén el volante firme y no aceleres hasta que la suspensión delantera apoye por completo antes de encarar la colosal recta de Conrod.",
        "curiosities": [
            "Conrod Straight mide casi 2 kilómetros; en 1987 se añadió la 'Chase' para reducir la velocidad punta tras accidentes que superaban los 300 km/h.",
            "Durante las carreras reales es habitual que los 'marshals' deban ondear banderas amarillas por la irrupción de canguros cruzando la pista a toda velocidad.",
            "El desnivel de 174 metros equivale a subir y bajar un rascacielos de 50 plantas en cada vuelta de 2 minutos."
        ]
    },
    {
        "name": "Brands Hatch",
        "slug": "brands-hatch",
        "category": "Real",
        "country": "Reino Unido",
        "country_code": "uk",
        "location": "West Kingsdown, Kent",
        "length_km": 3.91,
        "turns": 9,
        "elevation_m": 35.0,
        "longest_straight_m": 475.0,
        "layouts_count": 2,
        "time_progression": 1,
        "weather_change": 1,
        "laser_scanned": 1,
        "first_game": "Gran Turismo 6",
        "record_lap": "1:09.593 (Nigel Mansell, Williams FW11, 1986)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/3/3e/Brands_Hatch.jpg/revision/latest/scale-to-width-down/600?cb=20170104093040",
        "svg_path": "assets/tracks/brands_hatch.svg",
        "history_gt": "Incorporado con honores en GT6 en sus dos variantes: el circuito corto Indy Circuit y el legendario trazado completo de Gran Premio que se adentra en los tupidos bosques de Kent. Polyphony Digital capturó la famosa curva ciega en bajada Paddock Hill Bend con un detalle físico impecable, reproduciendo la compresión de amortiguadores que descoloca la zaga si no se balancea el acelerador.",
        "history_real": "Nacido como un circuito de hierba para motocross en 1926, Brands Hatch albergó 12 Grandes Premios de Gran Bretaña de Fórmula 1 alternándose con Silverstone entre 1964 y 1986. Escenario de la primera victoria de Nigel Mansell en F1 y de gloriosas batallas del BTCC (Campeonato Británico de Turismos) y DTM.",
        "driving_tips": "En Paddock Hill Bend debes frenar en línea recta antes de tirarte a ciegas hacia el vértice en profunda pendiente negativa: si tocas el freno con el coche apoyado harás un trompo inmediato. Druids exige frenada en subida muy tardía para abrirte y maximizar la tracción hacia Graham Hill Bend.",
        "curiosities": [
            "Paddock Hill Bend es apodada popularmente como 'la montaña rusa' por su repentino pozo gravitatorio de 25 metros de caída.",
            "En la variante Grand Prix, la mitad posterior del circuito transcurre bajo una densa bóveda de árboles centenarios con hojas cayendo sobre el asfalto.",
            "En GT6 cuenta con simulación climática completa de lluvia inglesa con asfalto reflectante."
        ]
    },
    {
        "name": "Circuit de Spa-Francorchamps",
        "slug": "spa-francorchamps",
        "category": "Real",
        "country": "Bélgica",
        "country_code": "belgica",
        "location": "Stavelot / Spa, Ardenas",
        "length_km": 7.00,
        "turns": 19,
        "elevation_m": 104.0,
        "longest_straight_m": 751.0,
        "layouts_count": 2,
        "time_progression": 1,
        "weather_change": 1,
        "laser_scanned": 1,
        "first_game": "Gran Turismo 5 (DLC) / GT6",
        "record_lap": "1:41.252 (Lewis Hamilton, Mercedes W11, 2020)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/f/ff/Spa-Francorchamps.jpg/revision/latest?cb=20230721142115",
        "svg_path": "assets/tracks/spa_francorchamps.svg",
        "history_gt": "Spa fue una de las obras cumbres del modelado de circuitos en GT6. Polyphony Digital implementó aquí su motor meteorológico más avanzado: debido a la orografía de las Ardenas, el juego reproduce microclimas donde puede estar lloviendo torrencialmente en Les Combes mientras la horquilla de La Source permanece con asfalto completamente seco. Incluye iluminación de focos nocturnos y estrellas reales.",
        "history_real": "Diseñado en 1920 utilizando las carreteras públicas entre Francorchamps, Malmedy y Stavelot, el trazado original medía 14 km y era aterradoramente rápido. Acoge anualmente el Gran Premio de Bélgica de Fórmula 1 y las 24 Horas de Spa. El complejo de curvas Eau Rouge-Raidillon es universalmente considerado el pasaje más icónico del motorsport mundial.",
        "driving_tips": "En Eau Rouge-Raidillon la clave es la confianza aerodinámica: encarrila el coche a la izquierda, roza el bordillo interior derecho y mantén el pie a fondo mientras la compresión aplasta el chasis en subida ciega hacia la recta de Kemmel. En Pouhon (curva 12 en bajada), mete quinta marcha y deja correr el coche sin ahogar el motor.",
        "curiosities": [
            "Con 7.004 metros, es el trazado permanente activo más largo de todo el calendario mundial de la Fórmula 1.",
            "La pendiente de subida en Raidillon alcanza un escalofriante 17% de inclinación.",
            "En GT6 puedes correr las 24 Horas de Spa con transición en tiempo real acelerada de atardecer, noche cerrada y amanecer con niebla en el valle."
        ]
    },
    {
        "name": "Nürburgring (Nordschleife & GP)",
        "slug": "nurburgring",
        "category": "Real",
        "country": "Alemania",
        "country_code": "alemania",
        "location": "Nürburg, Montañas de Eifel",
        "length_km": 20.83,
        "turns": 73,
        "elevation_m": 300.0,
        "longest_straight_m": 2135.0,
        "layouts_count": 4,
        "time_progression": 1,
        "weather_change": 1,
        "laser_scanned": 1,
        "first_game": "Gran Turismo 4",
        "record_lap": "5:19.546 (Timo Bernhard, Porsche 919 Hybrid Evo, 2018)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/4/41/N%C3%BCrburgring_Nordschleife.jpg/revision/latest/scale-to-width-down/600?cb=20161230070621",
        "svg_path": "assets/tracks/nurburgring_gp.svg",
        "history_gt": "El Nordschleife es la obsesión personal de Kazunori Yamauchi, quien compite habitualmente en las 24 Horas de Nürburgring reales a los mandos de Nissan GT-R y Lexus LFA oficiales de clase SP8T. Para GT6, los 20.8 km del 'Infierno Verde' fueron actualizados con los grafitis reales pintados en el asfalto, peraltes exactos del Karussell de hormigón y ciclo de 24 horas con lluvia torrencial y público con fogatas y tiendas de campaña en el bosque.",
        "history_real": "Construido en 1927 rodeando el castillo medieval de Nürburg en los montes de Eifel. Jackie Stewart lo bautizó para siempre como 'El Infierno Verde' ('The Green Hell'). Escenario del legendario Gran Premio de 1976 donde Niki Lauda sobrevivió a su gravísimo accidente con fuego, lo que puso fin a la F1 en el Nordschleife.",
        "driving_tips": "Aprende el ritmo fluido en lugar de atacar cada curva individualmente. En Flugplatz el coche se despega del suelo a más de 200 km/h: mantén el volante recto antes del salto. En el Karussell, entra con la rueda izquierda encajada en las placas peraltadas de hormigón para aprovechar el efecto 'riel' centrífugo.",
        "curiosities": [
            "Tiene 300 metros de desnivel absoluto entre su punto más alto (Hohe Acht, 620 m) y el más bajo (Breidscheid, 320 m).",
            "GT6 ofrece 4 variantes: Nordschleife clásica, Nürburgring 24h (combinado con el circuito GP moderno), Nürburgring GP/F y Nürburgring GP/D.",
            "Cualquier ciudadano con carnet de conducir puede acceder con su coche de calle pagando un peaje en los días de 'Touristenfahrten'."
        ]
    },
    {
        "name": "Circuit de la Sarthe (24 Heures du Mans)",
        "slug": "lemans",
        "category": "Real",
        "country": "Francia",
        "country_code": "francia",
        "location": "Le Mans, País del Loira",
        "length_km": 13.63,
        "turns": 38,
        "elevation_m": 37.3,
        "longest_straight_m": 2040.0,
        "layouts_count": 2,
        "time_progression": 1,
        "weather_change": 1,
        "laser_scanned": 1,
        "first_game": "Gran Turismo 4",
        "record_lap": "3:14.791 (Kamui Kobayashi, Toyota TS050 Hybrid, 2017)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/1/1f/Circuit_de_la_Sarthe_map.png/revision/latest/scale-to-width-down/600?cb=20250530065755",
        "svg_path": "assets/tracks/lemans.svg",
        "history_gt": "Recreado con obsesión científica en GT6. Polyphony Digital introdujo un motor de simulación astronómica que calcula la posición exacta del sol, la luna y las constelaciones de estrellas visibles en la noche de Le Mans basándose en la latitud y longitud real de la Sarthe (47°57'N, 0°12'E). Permite competir tanto en la variante moderna con las dos chicanes de Mulsanne como en la versión histórica sin chicanes donde los Grupo C superaban los 400 km/h.",
        "history_real": "Sede desde 1923 de las legendarias 24 Horas de Le Mans, la carrera de resistencia más prestigiosa del planeta y una de las tres joyas de la 'Triple Corona' del automovilismo (junto al GP de Mónaco y las 500 Millas de Indianápolis). Escenario del famoso duelo Ford vs Ferrari en los años 60 y del récord de 19 victorias de Porsche.",
        "driving_tips": "El compromiso aerodinámico es vital: necesitas carga aerodinámica baja para volar en los casi 6 km de la recta de Hunaudières, pero suficiente apoyo en las rápidas Curvas Porsche para no perder la trasera a 220 km/h. La frenada en la horquilla de Mulsanne se hace desde más de 330 km/h: frena antes del cartel de 200 m.",
        "curiosities": [
            "En 1988, el prototipo WM-Peugeot P88 pilotado por Roger Dorchy alcanzó 407 km/h en Mulsanne antes de que se construyeran las chicanes obligatorias en 1990.",
            "Más del 80% del trazado está formado por carreteras departamentales públicas francesas (D338 y D139) abiertas al tráfico civil durante todo el año.",
            "En GT6, el ciclo de 24 horas muestra las gradas llenas de fuegos artificiales y norias iluminadas cuando cae la medianoche."
        ]
    },
    {
        "name": "Mazda Raceway Laguna Seca",
        "slug": "laguna-seca",
        "category": "Real",
        "country": "Estados Unidos",
        "country_code": "usa",
        "location": "Monterey, California",
        "length_km": 3.60,
        "turns": 11,
        "elevation_m": 55.0,
        "longest_straight_m": 453.0,
        "layouts_count": 1,
        "time_progression": 0,
        "weather_change": 0,
        "laser_scanned": 1,
        "first_game": "Gran Turismo 2",
        "record_lap": "1:05.786 (Marc Gené, Ferrari F2003-GA, 2012)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/c/ce/Mazda_Raceway_Laguna_Seca.jpg/revision/latest?cb=20161230051707",
        "svg_path": "assets/tracks/laguna_seca.svg",
        "history_gt": "Laguna Seca ha sido un pilar fundamental de la saga Gran Turismo desde GT2 en PlayStation 1. En GT6, el trazado californiano fue reescaneado para reproducir fielmente la textura del asfalto abrasivo de Monterey, el calor seco del desierto y la infame caída ciega del Sacacorchos (The Corkscrew).",
        "history_real": "Construido en 1957 alrededor de un lecho seco de lago (de ahí su nombre en español), ha acogido carreras históricas de IndyCar, Can-Am, IMSA y MotoGP. Aquí tuvo lugar en 1996 el mítico adelantamiento 'The Pass' de Alex Zanardi sobre Bryan Herta tirándose por la tierra del Sacacorchos en la última vuelta.",
        "driving_tips": "El Sacacorchos (curvas 8 y 8A) se aborda a ciegas apuntando al árbol solitario en la loma: frena recto en la cresta, gira hacia el piano interior izquierdo mientras la pista desaparece 18 metros bajo tus ruedas y déjate caer hacia el vértice derecho con suavidad. La curva 2 (Andretti Hairpin) es una doble horquilla con fuerte frenada en pendiente.",
        "curiosities": [
            "La caída vertical del Sacacorchos equivale a precipitarse en picado por el hueco de un edificio de cinco pisos y medio en apenas 3 segundos.",
            "En MotoGP 2008, Valentino Rossi emuló a Zanardi adelantando a Casey Stoner por la tierra de la escapatoria exterior del Sacacorchos.",
            "En GT6 es uno de los circuitos oficiales seleccionados para las pruebas contrarreloj de la fase clasificatoria de la GT Academy."
        ]
    },
    {
        "name": "Willow Springs International Raceway",
        "slug": "willow-springs",
        "category": "Real",
        "country": "Estados Unidos",
        "country_code": "usa",
        "location": "Rosamond, Desierto de Mojave, California",
        "length_km": 4.02,
        "turns": 9,
        "elevation_m": 30.0,
        "longest_straight_m": 756.0,
        "layouts_count": 2,
        "time_progression": 1,
        "weather_change": 0,
        "laser_scanned": 1,
        "first_game": "Gran Turismo 6",
        "record_lap": "1:06.300 (Michael Andretti, Lola T98/00 IndyCar, 1998)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/e/e5/Willow_Springs.jpg/revision/latest/scale-to-width-down/598?cb=20151103144301",
        "svg_path": "assets/tracks/willow_springs.svg",
        "history_gt": "Una de las grandes primicias de Gran Turismo 6. Kazunori Yamauchi y el equipo de Polyphony Digital pasaron semanas en el desierto de Mojave escaneando 'Big Willow' y la variante técnica 'Streets of Willow Springs'. El cielo del atardecer con tonalidades naranjas y púrpuras sobre el desierto californiano es uno de los efectos visuales más aclamados del juego.",
        "history_real": "Inaugurado en 1953, Willow Springs es el circuito permanente más antiguo de Norteamérica y fue declarado Monumento Histórico de California. Apodado 'The Fastest Road in the West' (El circuito más rápido del Oeste), sus curvas peraltadas a alta velocidad han servido como banco de pruebas para Carroll Shelby con el Shelby Cobra y Hollywood para rodajes de carreras.",
        "driving_tips": "La curva 8 es un radio monstruoso a derechas que se toma a más de 230 km/h: si levantas el pie bruscamente en pleno apoyo provocarás un trompo violento que te lanzará contra el desierto. La curva 9 conecta directamente con la recta principal; el coche irá derivando hacia el bordillo exterior con la rueda delantera izquierda trabajando al límite térmico.",
        "curiosities": [
            "No tiene casi escapatorias de asfalto ni barreras de neumáticos tradicionales: el circuito está rodeado directamente por tierra salvaje y matorrales del desierto.",
            "Fue utilizado por Ken Miles y Carroll Shelby en 1965 para desarrollar el legendario Ford GT40 que ganaría las 24 Horas de Le Mans.",
            "En GT6 incluye la variante 'Streets of Willow', un trazado ratonero con saltos ciegos ideales para coches de tracción delantera y turismos ligeros."
        ]
    },
    {
        "name": "Ascari Race Resort",
        "slug": "ascari",
        "category": "Real",
        "country": "España",
        "country_code": "espana",
        "location": "Ronda, Málaga, Andalucía",
        "length_km": 5.42,
        "turns": 26,
        "elevation_m": 40.0,
        "longest_straight_m": 470.0,
        "layouts_count": 1,
        "time_progression": 0,
        "weather_change": 0,
        "laser_scanned": 1,
        "first_game": "Gran Turismo 6",
        "record_lap": "1:47.382 (Kamui Kobayashi, Benetton B197 F1)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/8/88/Ascari_Race_Resort.jpg/revision/latest/scale-to-width-down/523?cb=20160208165124",
        "svg_path": "assets/tracks/ascari.svg",
        "history_gt": "Ascari tuvo un protagonismo monumental en Gran Turismo 6: fue la sede elegida por Sony PlayStation para la presentación mundial de lanzamiento del juego en diciembre de 2013. Para conmemorar el evento, la ciudad de Ronda inauguró una calle oficial con el nombre del creador del juego: 'Paseo de Kazunori Yamauchi'. Es el circuito español más largo recreado con escaneo láser en la saga.",
        "history_real": "Construido en 2003 por el multimillonario e ingeniero holandés Klaas Zwart, Ascari es un circuito privado de superlujo enclavado en las montañas de Ronda. Sus 26 curvas están inspiradas y bautizadas en honor a los pasajes más míticos del automovilismo: tiene curvas dedicadas a Daytona, Spa-Francorchamps, Silverstone, Nürburgring y Bathurst.",
        "driving_tips": "Con 26 curvas entrelazadas sin apenas descanso, la clave en Ascari es memorizar los enlaces rítmicos. Las curvas peraltadas estilo Daytona permiten mantener velocidades de paso altísimas; configura la dureza de la barra estabilizadora delantera media-baja para que el coche copie bien los cambios de rasante.",
        "curiosities": [
            "Es el circuito de velocidad más largo de toda España (5,425 metros), superando en longitud al Circuit de Barcelona-Catalunya y al Circuito de Jerez.",
            "Lleva su nombre en honor a Alberto Ascari, el primer bicampeón del mundo de Fórmula 1 con Ferrari (1952 y 1953).",
            "La presentación de GT6 en Ronda incluyó la transformación visual completa de la plaza de toros histórica y la rotulación de las calles del casco antiguo con la identidad de Gran Turismo."
        ]
    },
    {
        "name": "Goodwood Hillclimb",
        "slug": "goodwood",
        "category": "Real",
        "country": "Reino Unido",
        "country_code": "uk",
        "location": "Chichester, West Sussex",
        "length_km": 1.86,
        "turns": 9,
        "elevation_m": 57.0,
        "longest_straight_m": 290.0,
        "layouts_count": 1,
        "time_progression": 0,
        "weather_change": 0,
        "laser_scanned": 1,
        "first_game": "Gran Turismo 6",
        "record_lap": "39.08s (Max Chilton, McMurtry Spéirling, 2022)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/2/2f/Goodwood_Hillclimb.jpg/revision/latest/scale-to-width-down/600?cb=20150827071124",
        "svg_path": "assets/tracks/goodwood.svg",
        "history_gt": "Una exclusiva mundial sin precedentes para Gran Turismo 6. El Duque de Richmond colaboró directamente con Kazunori Yamauchi para trasladar el Festival of Speed de Goodwood al mundo de los videojuegos. La subida a la colina cuenta con la mítica escultura central frente a Goodwood House y el icónico muro de sílex ('Flint Wall').",
        "history_real": "Celebrado anualmente en los terrenos señoriales de Goodwood House desde 1993, el Festival of Speed es el mayor homenaje al automovilismo histórico y moderno del mundo, reuniendo desde coches de Gran Premio de la era eduardiana de principios del siglo XX hasta los monoplazas más recientes de Fórmula 1 y prototipos de Le Mans.",
        "driving_tips": "El trazado es extremadamente estrecho y está flanqueado por fardos de paja que no perdonan ningún desvío: no busques el vértice atacando con bordillos porque tocar la hierba o los fardos provocará la descalificación inmediata de la prueba de tiempo. En el paso frente al 'Flint Wall' modula el gas sin tocar el muro de piedra.",
        "curiosities": [
            "Nick Heidfeld ostentó el récord oficial histórico durante más de dos décadas con un McLaren MP4/13 de Fórmula 1 (41.6s en 1999).",
            "En el Festival real, cada año se erige una escultura monumental de más de 30 metros de altura frente a la mansión dedicada a una marca fabricante distinta.",
            "En GT6 se organizan los desafíos oficiales de Goodwood por rondas eliminatorias con vehículos clásicos como el Alfa Romeo TZ2 y el Red Bull X2014."
        ]
    },
    {
        "name": "Autodromo Nazionale Monza",
        "slug": "monza",
        "category": "Real",
        "country": "Italia",
        "country_code": "italia",
        "location": "Monza, Lombardía",
        "length_km": 5.79,
        "turns": 11,
        "elevation_m": 12.0,
        "longest_straight_m": 1195.0,
        "layouts_count": 2,
        "time_progression": 1,
        "weather_change": 1,
        "laser_scanned": 1,
        "first_game": "Gran Turismo 5 / GT6",
        "record_lap": "1:18.887 (Lewis Hamilton, Mercedes W11, 2020)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/8/8f/Autodromo_Nazionale_Monza.jpg/revision/latest?cb=20180127020052",
        "svg_path": "assets/tracks/monza.svg",
        "history_gt": "En GT6, Monza recibió el tratamiento completo de transición horaria y meteorológica. El parque real de Monza luce árboles otoñales y el viejo óvalo peraltado de hormigón 'Pista di Alta Velocità' de 1955 se puede admirar al pasar por la recta principal. Incluye la variante con chicanes y el trazado sin chicanes donde se rozan velocidades estratosféricas.",
        "history_real": "Construido en 1922 en apenas 110 días, es el circuito de carreras permanente más antiguo de Europa continental y el 'Templo de la Velocidad' de la Fórmula 1 y los apasionados 'tifosi' de Ferrari. Es la carrera con la velocidad media más alta del campeonato mundial (más de 260 km/h).",
        "driving_tips": "La frenada de la Variante del Rettifilo se realiza desde 350 km/h hasta 70 km/h en primera marcha: frena exactamente en el cartel de 150 metros y mantén el volante recto. En la mítica Curva Parabólica (Curva Alboreto), abre la trazada y pisa el acelerador progresivamente para aprovechar toda la escapatoria hacia la línea de meta.",
        "curiosities": [
            "Es el circuito que ha albergado más Grandes Premios de Fórmula 1 en la historia (todos desde 1950 excepto en 1980 en Imola).",
            "El óvalo peraltado original tenía una inclinación de hasta 38 grados y fue escenario de la película clásica 'Grand Prix' de John Frankenheimer (1966).",
            "El rebufo en Monza es tan poderoso que permite ganar hasta 15-20 km/h adicionales al seguir de cerca a un rival en la recta Rettifilo."
        ]
    },
    {
        "name": "Daytona International Speedway",
        "slug": "daytona",
        "category": "Real",
        "country": "Estados Unidos",
        "country_code": "usa",
        "location": "Daytona Beach, Florida",
        "length_km": 5.73,
        "turns": 12,
        "elevation_m": 9.0,
        "longest_straight_m": 914.0,
        "layouts_count": 2,
        "time_progression": 1,
        "weather_change": 1,
        "laser_scanned": 1,
        "first_game": "Gran Turismo 5 Prologue / GT6",
        "record_lap": "1:33.685 (Oliver Jarvis, Mazda RT24-P DPi, 2019)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/8/86/Daytona_Tri-Oval.png/revision/latest/scale-to-width-down/545?cb=20251212073725",
        "svg_path": "assets/tracks/daytona.svg",
        "history_gt": "Presente con el Tri-Oval de 2.5 millas y el Road Course de las 24 Horas de Daytona. Polyphony Digital modeló con precisión física la banca peraltada de 31 grados, transmitiendo a través del volante Force Feedback la enorme fuerza G descendente que comprime los neumáticos contra el muro en los óvalos.",
        "history_real": "Inaugurado en 1959 por el fundador de NASCAR Bill France Sr. para sustituir las carreras en la arena de la playa de Daytona Beach. Sede anual de la prestigiosa Daytona 500 ('The Great American Race') y de las 24 Horas de Daytona (Rolex 24) del campeonato IMSA SportsCar.",
        "driving_tips": "En el trazado Road Course, la frenada para entrar al Infield desde el peralte a más de 300 km/h es crítica: la transición de superficie peraltada a plano descoloca el equilibrio de frenos; ajusta el reparto de frenos 6/4 hacia delante para evitar bloqueos del eje trasero.",
        "curiosities": [
            "El peralte de 31 grados en las curvas 1 y 4 es tan pronunciado que es imposible mantenerse de pie sobre el asfalto sin resbalar hacia abajo.",
            "En las pruebas de NASCAR en GT6, los coches ruedan pegados puerta con puerta a escasos milímetros a más de 320 km/h en 'Drafting Pack'.",
            "Cuenta con una pista de aterrizaje para avionetas privadas en el centro del lago Lloyd dentro del 'infield'."
        ]
    },
    {
        "name": "Indianapolis Motor Speedway",
        "slug": "indianapolis",
        "category": "Real",
        "country": "Estados Unidos",
        "country_code": "usa",
        "location": "Speedway, Indiana",
        "length_km": 4.19,
        "turns": 16,
        "elevation_m": 3.0,
        "longest_straight_m": 1006.0,
        "layouts_count": 2,
        "time_progression": 0,
        "weather_change": 0,
        "laser_scanned": 1,
        "first_game": "Gran Turismo 4",
        "record_lap": "1:10.399 (Rubens Barrichello, Ferrari F2004, 2004)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/7/79/Indianapolis_Motor_Speedway.jpg/revision/latest/scale-to-width-down/600?cb=20160403090628",
        "svg_path": "assets/tracks/indianapolis.svg",
        "history_gt": "El legendario 'Brickyard' está modelado en GT6 con sus dos almas: el clásico óvalo rectangular de 2.5 millas y el técnico trazado interior Road Course utilizado por la Fórmula 1 y MotoGP. Incluye la icónica torre de control Pagoda y la línea de meta pavimentada con una yarda de ladrillos originales de 1909.",
        "history_real": "Construido en 1909 y pavimentado originalmente con 3.2 millones de ladrillos, Indianápolis es el segundo recinto deportivo de carreras más antiguo del mundo y el recinto deportivo con mayor aforo del planeta (más de 300,000 espectadores). Es la sede de las 500 Millas de Indianápolis (Indy 500), parte de la Triple Corona.",
        "driving_tips": "En el óvalo rectangular, cada una de las 4 esquinas tiene exactamente 9 grados y 12 minutos de peralte: mantén una línea muy limpia pegado a la línea blanca interior y no des bandazos con la dirección para evitar pérdida de velocidad punta por arrastre de neumáticos.",
        "curiosities": [
            "La tradición exige que el ganador de las 500 Millas bese la yarda de ladrillos ('The Yard of Bricks') y beba una botella de leche fresca en el podio.",
            "En su interior cabrían holgadamente el Coliseo de Roma, el Vaticano, el Taj Mahal, la Casa Blanca y el estadio de los Yankees juntos.",
            "Albergó el Gran Premio de Estados Unidos de F1 de 2000 a 2007, incluyendo el recordado fiasco de Michelin en 2005 donde solo compitieron 6 monoplazas."
        ]
    },
    {
        "name": "Twin Ring Motegi",
        "slug": "twin-ring-motegi",
        "category": "Real",
        "country": "Japón",
        "country_code": "japon",
        "location": "Motegi, Prefectura de Tochigi",
        "length_km": 4.80,
        "turns": 14,
        "elevation_m": 30.0,
        "longest_straight_m": 762.0,
        "layouts_count": 4,
        "time_progression": 1,
        "weather_change": 1,
        "laser_scanned": 1,
        "first_game": "Gran Turismo 4",
        "record_lap": "1:44.022 (Marc Márquez, Honda RC213V MotoGP, 2014)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/8/8d/Twin_Ring_Motegi.jpg/revision/latest/scale-to-width-down/600?cb=20160204081128",
        "svg_path": "assets/tracks/motegi.svg",
        "history_gt": "Propiedad de Honda Motor Company, Motegi está recreado en GT6 con sus cuatro trazados completos: el Road Course principal, el óvalo Super Speedway de 1.5 millas (anteriormente usado por IndyCar) y los trazados East y West Course. La pista discurre pasando por debajo de los puentes del óvalo con un trazado stop-and-go exigente para los frenos.",
        "history_real": "Inaugurado en 1997 por Honda, su nombre 'Twin Ring' se debe a la coexistencia de dos circuitos independientes: el circuito de Gran Premio de carretera y el óvalo peraltado americano. Es la sede anual del Gran Premio de Japón de MotoGP y de rondas del Super GT y Super Formula.",
        "driving_tips": "Motegi es un circuito puramente de frenadas fuertes y aceleración (Stop and Go): configura unos frenos potentes y un mapa de acelerador suave. La recta trasera en bajada culmina en una frenada brutal de 90 grados hacia el túnel del óvalo; retrasa la frenada y usa el freno motor.",
        "curiosities": [
            "Alberga en su interior el 'Honda Collection Hall', el museo oficial donde se exhiben más de 350 vehículos de carreras históricos de Honda.",
            "Fue dañado por el terremoto y tsunami de Tohoku en marzo de 2011, lo que obligó a reasfaltar sectores completos de la pista.",
            "En GT6 cuenta con ciclo día/noche y carreras de resistencia de 2 y 4 horas."
        ]
    },
    {
        "name": "Suzuka Circuit",
        "slug": "suzuka",
        "category": "Real",
        "country": "Japón",
        "country_code": "japon",
        "location": "Suzuka, Prefectura de Mie",
        "length_km": 5.81,
        "turns": 18,
        "elevation_m": 52.7,
        "longest_straight_m": 900.0,
        "layouts_count": 3,
        "time_progression": 1,
        "weather_change": 1,
        "laser_scanned": 1,
        "first_game": "Gran Turismo 4",
        "record_lap": "1:27.064 (Sebastian Vettel, Ferrari SF90, 2019)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/f/fb/Suzuka_Circuit.jpg/revision/latest?cb=20171217022009",
        "svg_path": "assets/tracks/suzuka.svg",
        "history_gt": "El circuito favorito de los pilotos de todo el mundo y banco de pruebas histórico de la saga Gran Turismo. Modelado al detalle con su diseño único en forma de '8', con el paso elevado sobre la recta trasera. En GT6, Suzuka cuenta con clima dinámico de lluvia torrencial, niebla en las enlazadas y transición de iluminación desde la tarde hasta la noche.",
        "history_real": "Diseñado en 1962 por el neerlandés John Hugenholtz como pista de pruebas para Honda. Es la sede histórica indiscutible del Gran Premio de Japón de Fórmula 1 y las 8 Horas de Resistencia de Motociclismo de Suzuka. Escenario de las míticas y polémicas colisiones por el campeonato mundial entre Ayrton Senna y Alain Prost en 1989 y 1990.",
        "driving_tips": "El primer sector ('Las Eses') exige sincronización quirúrgica: si entras pasado en la primera curva, arruinarás las cuatro siguientes por acumulación de inercia negativa. En la temible curva 130R a izquierdas a más de 280 km/h, mantén el acelerador a fondo sólo si llevas carga aerodinámica suficiente.",
        "curiosities": [
            "Es el único circuito de Fórmula 1 en el mundo con un trazado en forma de ocho con puente y túnel de cruce.",
            "La icónica noria gigante del parque de atracciones 'MOTOPIA' al fondo de la recta principal está iluminada en carreras nocturnas en GT6.",
            "Incluye en GT6 tres configuraciones: Grand Prix Circuit, Suzuka East Course y Suzuka West Course."
        ]
    },
    {
        "name": "Fuji Speedway",
        "slug": "fuji-speedway",
        "category": "Real",
        "country": "Japón",
        "country_code": "japon",
        "location": "Oyama, Prefectura de Shizuoka",
        "length_km": 4.56,
        "turns": 16,
        "elevation_m": 40.0,
        "longest_straight_m": 1475.0,
        "layouts_count": 2,
        "time_progression": 1,
        "weather_change": 1,
        "laser_scanned": 1,
        "first_game": "Gran Turismo 4",
        "record_lap": "1:18.426 (Felipe Massa, Ferrari F2008, 2008)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/6/66/Fuji_Speedway_%28Old%29.jpg/revision/latest/scale-to-width-down/600?cb=20160116164409",
        "svg_path": "assets/tracks/fuji.svg",
        "history_gt": "Propiedad de Toyota Motor Corporation, Fuji Speedway fue recreado en GT6 con su gigantesca recta de 1.47 kilómetros y la silueta del imponente Monte Fuji nevado recortada en el horizonte. Ofrece dos trazados: Fuji F (con la chicane final técnica) y Fuji GT (con la curva rápida hacia la recta principal).",
        "history_real": "Inaugurado en 1965 a los pies del volcán sagrado, albergó el primer Gran Premio de Japón de F1 en 1976 bajo un diluvio legendario donde Niki Lauda decidió retirarse por seguridad y James Hunt se coronó campeón. Remodelado en 2005 por Hermann Tilke, acoge las 6 Horas de Fuji del WEC.",
        "driving_tips": "La recta principal de casi 1.5 km premia marchas largas y baja resistencia al avance, pero el sector final (curvas 10 a 16) es sumamente lento y técnico en subida. La frenada de la curva 1 es ciega y cuesta abajo: frena fuerte en el poste de 150 metros y evita abrirte en exceso.",
        "curiosities": [
            "Su recta de 1,475 metros es una de las más largas de cualquier circuito de competición internacional.",
            "En el trazado original de los años 60 existía la curva peraltada 'Daiichi' de 30 grados, una de las más peligrosas de la historia del automovilismo.",
            "En GT6, el clima de Fuji reproduce las repentinas nieblas densas que descienden desde las faldas del monte."
        ]
    },
    {
        "name": "Tsukuba Circuit",
        "slug": "tsukuba",
        "category": "Real",
        "country": "Japón",
        "country_code": "japon",
        "location": "Shimotsuma, Prefectura de Ibaraki",
        "length_km": 2.05,
        "turns": 8,
        "elevation_m": 5.3,
        "longest_straight_m": 437.0,
        "layouts_count": 1,
        "time_progression": 0,
        "weather_change": 1,
        "laser_scanned": 1,
        "first_game": "Gran Turismo 4",
        "record_lap": "49.445s (Tomohiko 'Under' Suzuki, Nissan Silvia S15 Scorch Racing, 2020)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/7/7c/Tsukuba_Circuit.jpg/revision/latest?cb=20180413112947",
        "svg_path": "assets/tracks/tsukuba.svg",
        "history_gt": "Tsukuba es la vara de medir por antonomasia de la cultura automotriz japonesa. Todo aficionado a Gran Turismo ha probado aquí la aceleración, frenada y maniobrabilidad de cada deportivo. En GT6 está reproducido milimétricamente con sus pianos estrechos y asfalto engomado por décadas de batallas de drift y time attack.",
        "history_real": "Construido en 1970, Tsukuba es famoso en todo el planeta por ser el escenario de las pruebas y batallas del programa de televisión 'Best Motoring' y 'Hot Version' conducido por Keiichi Tsuchiya ('Drift King'). Bajar del minuto (sub-60 segundos) en Tsukuba es el santo grial de los preparadores de tuning de Japón.",
        "driving_tips": "En la última curva a derechas ('Final Corner') debes entrar frenando en apoyo suave y mantener una aceleración continua rozando el bordillo interior para salir disparado a la recta principal. En las dos horquillas Dunlop cierra el radio para acelerar temprano.",
        "curiosities": [
            "Con sólo 2,045 metros de longitud, una vuelta rápida dura menos de un minuto en un superdeportivo.",
            "Es el circuito de referencia estándar utilizado por ingenieros de Nismo, Spoon, Mugen, Mine's y HKS para afinar sus coches de calle.",
            "En GT6 cuenta con la variante bajo lluvia que pone a prueba la motricidad de los coches de propulsión trasera."
        ]
    },
    {
        "name": "Red Bull Ring",
        "slug": "red-bull-ring",
        "category": "Real",
        "country": "Austria",
        "country_code": "austria",
        "location": "Spielberg, Estiria",
        "length_km": 4.33,
        "turns": 10,
        "elevation_m": 65.0,
        "longest_straight_m": 860.0,
        "layouts_count": 2,
        "time_progression": 1,
        "weather_change": 1,
        "laser_scanned": 1,
        "first_game": "Gran Turismo 6 (Actualización 1.09)",
        "record_lap": "1:05.619 (Carlos Sainz, McLaren MCL35, 2020)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/7/75/Red_Bull_Ring.jpg/revision/latest?cb=20181109061053",
        "svg_path": "assets/tracks/red_bull_ring.svg",
        "history_gt": "Añadido de forma gratuita en la actualización 1.09 de Gran Turismo 6 en junio de 2014, coincidiendo con el regreso del Gran Premio de Austria de F1 tras 11 años de ausencia. Polyphony Digital implementó tanto el trazado de Gran Premio como el trazado corto para pruebas de turismos, con ciclo de 24 horas y clima de lluvia.",
        "history_real": "Originalmente inaugurado en 1969 como el temible y ultra-rápido Österreichring, fue rediseñado por Hermann Tilke en 1996 como A1-Ring y finalmente adquirido y reconstruido por Dietrich Mateschitz de Red Bull, reabriendo en 2011 con la imponente escultura de acero del 'Toro de Spielberg' en el centro de la colina.",
        "driving_tips": "El circuito está compuesto por tres rectas en subida seguidas de curvas lentas de 90 grados: los tres primeros puntos de frenada son zonas óptimas de adelantamiento. Las curvas 9 y 10 (Rindt) en bajada exigen aprovechar al milímetro el bordillo exterior sin superar los límites de pista.",
        "curiosities": [
            "Es una de las pistas con menor número de curvas de todo el calendario internacional (solo 10 curvas oficiales).",
            "La estatua del toro de acero y bronce que preside el circuito mide 18 metros de altura y pesa 68 toneladas.",
            "En GT6 permite admirar el paisaje alpino de Estiria bañado por el sol del atardecer con iluminación HDR."
        ]
    },

    # ==========================================
    # 2. CIRCUITOS ORIGINALES DE POLYPHONY DIGITAL
    # ==========================================
    {
        "name": "Matterhorn",
        "slug": "matterhorn",
        "category": "Original",
        "country": "Suiza",
        "country_code": "suiza",
        "location": "Zermatt, Alpes Peninos",
        "length_km": 3.84,
        "turns": 15,
        "elevation_m": 88.0,
        "longest_straight_m": 530.0,
        "layouts_count": 4,
        "time_progression": 1,
        "weather_change": 0,
        "laser_scanned": 0,
        "first_game": "Gran Turismo 6",
        "record_lap": "1:22.450 (Referencia GT Academy, Nissan GT-R Nismo)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/d/dd/Matterhorn.jpg/revision/latest/scale-to-width-down/600?cb=20151122150109",
        "svg_path": "assets/tracks/matterhorn.svg",
        "history_gt": "Diseñado exclusivamente para el lanzamiento de Gran Turismo 6, Matterhorn fue la demostración técnica del nuevo motor gráfico de iluminación de Polyphony Digital. Situado en las laderas alpinas de Zermatt frente al icónico monte Cervino/Matterhorn de 4,478 m, el circuito cuenta con cuatro variantes (Riffelsee, Mer de Glace, Zermatt y Drot) con pendientes verticales que superan el 15% de desnivel.",
        "history_real": "Inspirado en las rutas de montaña alpinas cerradas como el Gornergrat y las pistas de servicio del teleférico de Zermatt. Aunque es un trazado ficticio, reproduce con precisión geográfica las vistas panorámicas del glaciar de Gorner y los pastos alpinos suizos.",
        "driving_tips": "Los cambios de rasante son tan abruptos que las ruedas delanteras pierden todo contacto con el suelo en varias crestas: frena antes de la cima para no aterrizar con las ruedas bloqueadas. Eleva la altura de la suspensión en el menú de setup para evitar que el fondo plano golpee el asfalto.",
        "curiosities": [
            "El monte Matterhorn/Cervino que se alza majestuoso de fondo es la montaña más fotografiada del planeta y el símbolo del chocolate Toblerone.",
            "La variante 'Riffelsee' incluye un salto ciego en bajada donde los coches vuelan literalmente durante más de 10 metros.",
            "Fue uno de los circuitos más votados por la comunidad de simracing de GT6 para los eventos contrarreloj semanales."
        ]
    },
    {
        "name": "Circuito de la Sierra",
        "slug": "circuito-de-la-sierra",
        "category": "Original",
        "country": "España",
        "country_code": "espana",
        "location": "Zahara de la Sierra, Cádiz, Andalucía",
        "length_km": 27.00,
        "turns": 112,
        "elevation_m": 350.0,
        "longest_straight_m": 1200.0,
        "layouts_count": 1,
        "time_progression": 1,
        "weather_change": 1,
        "laser_scanned": 0,
        "first_game": "Gran Turismo 6 (Actualización 1.12)",
        "record_lap": "7:55.120 (Referencia GT6, Red Bull X2014 Junior)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/d/d0/Circuito_de_la_Sierra.jpg/revision/latest?cb=20160202153052",
        "svg_path": "assets/tracks/sierra.svg",
        "history_gt": "El circuito más colosal y largo de toda la historia de Gran Turismo (27 kilómetros), superando incluso al Nordschleife de Nürburgring. Introducido en la actualización 1.12 junto con el modo 'Rally Sierra Time Attack', rodea el embalse de Zahara de la Sierra en la provincia de Cádiz con puentes, presas y pueblos blancos andaluces recreados con ciclo día/noche completo.",
        "history_real": "Basado en la carretera de montaña real A-2300 que rodea el Parque Natural de Grazalema y el embalse de Zahara-El Gastor. Las casas encaladas de blanco, los olivares y el castillo nazarí de Zahara son monumentos históricos reales de Andalucía.",
        "driving_tips": "Aprenderse 27 km y más de 100 curvas requiere sesiones completas de memorización. La carretera es estrecha y cuenta con guardarraíles metálicos continuos; mantén una puesta a punto blanda de amortiguadores para absorber los baches de asfalto secundario de montaña.",
        "curiosities": [
            "Con 27,000 metros de longitud, se tarda cerca de 10 minutos en completar una sola vuelta en un coche deportivo medio.",
            "Introdujo un minijuego exclusivo de puntos de adelantamiento, combos de velocidad y recarga de nitroso.",
            "Fue modelado por el equipo de Polyphony Digital tras realizar un viaje de exploración en helicóptero por la sierra de Cádiz."
        ]
    },
    {
        "name": "Grand Valley Speedway",
        "slug": "grand-valley",
        "category": "Original",
        "country": "Original",
        "country_code": "gran_turismo",
        "location": "Valle Costero Ficticio",
        "length_km": 4.95,
        "turns": 16,
        "elevation_m": 19.7,
        "longest_straight_m": 995.0,
        "layouts_count": 2,
        "time_progression": 0,
        "weather_change": 0,
        "laser_scanned": 0,
        "first_game": "Gran Turismo 1 (1997)",
        "record_lap": "1:32.400 (Nissan GT-R GT500)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/c/c5/Grand_Valley_Map.png/revision/latest/scale-to-width-down/600?cb=20221023224015",
        "svg_path": "assets/tracks/grand_valley.svg",
        "history_gt": "El circuito original definitivo de la saga Gran Turismo, presente desde la primera entrega de 1997 en PlayStation 1. Con su emblemático puente azul colgante, los dos túneles gemelos tallados en la roca y la horquilla en subida tras la curva 1. En GT6 cuenta con un modelado de follaje y agua del océano fotorrealista.",
        "history_real": "Diseñado desde cero por Kazunori Yamauchi y los ingenieros pioneros de Polyphony Digital como el circuito ideal donde poner a prueba la dinámicas de chasis y aerodinámica de cualquier coche.",
        "driving_tips": "La curva 1 tras la recta de meta es un curvón de radio amplio en bajada: mantén una trazada amplia para no comprometer la salida hacia la horquilla. La chicana rápida previa a la entrada del puente azul se toma rozando los dos bordillos en tercera marcha.",
        "curiosities": [
            "Ha aparecido en todos los juegos numéricos de Gran Turismo desde 1997.",
            "El puente colgante azul sobre el océano es uno de los iconos visuales más reconocibles de la historia de los videojuegos.",
            "Cuenta con la variante 'Grand Valley East', una versión recortada de 3.0 km ideal para turismos de baja cilindrada."
        ]
    },
    {
        "name": "Trial Mountain Circuit",
        "slug": "trial-mountain",
        "category": "Original",
        "country": "Original",
        "country_code": "gran_turismo",
        "location": "Sierra Montañosa Ficticia",
        "length_km": 3.98,
        "turns": 15,
        "elevation_m": 50.8,
        "longest_straight_m": 395.0,
        "layouts_count": 2,
        "time_progression": 0,
        "weather_change": 0,
        "laser_scanned": 0,
        "first_game": "Gran Turismo 1 (1997)",
        "record_lap": "1:24.150 (Castrol TOM'S Supra)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/5/59/Trial_Mountain_GT7_Map.png/revision/latest/scale-to-width-down/600?cb=20211021005415",
        "svg_path": "assets/tracks/trial_mountain.svg",
        "history_gt": "Presente desde el debut de la saga en 1997, Trial Mountain es el circuito montañoso más querido por los jugadores. Destaca por sus túneles de roca natural, densos bosques de coníferas, acantilados escarpados y la mítica chicana final con bordillo peraltado donde los coches despegan dos ruedas en el aire.",
        "history_real": "Inspirado en trazados clásicos de montaña como Nürburgring Nordschleife y Bathurst, pero compactado en un bucle frenético de 4 kilómetros.",
        "driving_tips": "El primer sector serpentea en subida entre paredes rocosas: no toques las paredes con la aleta o perderás toda la inercia. En la chicana final antes de meta, ataca el bordillo interior derecho con decisión para cortar la trayectoria recta hacia la bandera a cuadros.",
        "curiosities": [
            "Existe una leyenda urbana clásica en la comunidad sobre la silueta del monstruo del Lago Ness oculta en el lago del circuito.",
            "El salto de la chicana final es el lugar preferido de los jugadores en el modo Foto para capturar coches volando en pleno apoyo.",
            "En GT6 permite carreras en sentido inverso ('Reverse Layout')."
        ]
    },
    {
        "name": "Deep Forest Raceway",
        "slug": "deep-forest",
        "category": "Original",
        "country": "Original",
        "country_code": "gran_turismo",
        "location": "Bosque Templado Ficticio",
        "length_km": 3.60,
        "turns": 15,
        "elevation_m": 45.1,
        "longest_straight_m": 414.0,
        "layouts_count": 2,
        "time_progression": 0,
        "weather_change": 0,
        "laser_scanned": 0,
        "first_game": "Gran Turismo 1 (1997)",
        "record_lap": "1:15.890 (Nissan Skyline GT-R R34)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/6/60/Deep_Forest_Raceway_%28GT7%29.png/revision/latest/scale-to-width-down/600?cb=20220727143550",
        "svg_path": "assets/tracks/deep_forest.svg",
        "history_gt": "Inmortalizado desde 1997, Deep Forest es un circuito caracterizado por su fluidez técnica continua. Transcurre a través de densos desfiladeros boscosos con túneles semicubiertos y curvas ciegas enlazadas donde el coche apenas rueda con la dirección recta.",
        "history_real": "Concebido por Yamauchi como un templo del equilibrio mecánico y la transferencia de masas sin recurrir a largas rectas de potencia bruta.",
        "driving_tips": "La curva 1 se aborda en subida con peralte positivo; mantén el gas constante para no descargar el tren trasero. La última curva parabólica en bajada hacia meta requiere esperar pacientemente el punto de contacto antes de pisar el acelerador a fondo.",
        "curiosities": [
            "Es uno de los circuitos predilectos para carreras monocopa de deportivos japoneses de tracción trasera como el Mazda MX-5 y el Toyota AE86.",
            "Los túneles de roca cuentan en GT6 con efectos de sonido ambiental con reverberación acústica realista.",
            "Tiene una versión en sentido inverso extremadamente desafiante en bajada."
        ]
    },
    {
        "name": "High Speed Ring",
        "slug": "high-speed-ring",
        "category": "Original",
        "country": "Original",
        "country_code": "gran_turismo",
        "location": "Litoral Ficticio",
        "length_km": 4.00,
        "turns": 6,
        "elevation_m": 8.5,
        "longest_straight_m": 1010.0,
        "layouts_count": 2,
        "time_progression": 1,
        "weather_change": 1,
        "laser_scanned": 0,
        "first_game": "Gran Turismo 1 (1997)",
        "record_lap": "1:02.100 (Sauber Mercedes C9)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/f/f3/High_Speed_Ring_GT7_Map.png/revision/latest/scale-to-width-down/600?cb=20211021011757",
        "svg_path": "assets/tracks/high_speed_ring.svg",
        "history_gt": "El circuito más rápido de la primera era de Gran Turismo. Con dos curvas peraltadas monumentales y un puente elevado sobre la curva 2. En GT6 recibió clima de lluvia y ciclo de luz, convirtiéndose en el escenario predilecto para medir la velocidad punta de prototipos de Le Mans y coches de la serie Red Bull X.",
        "history_real": "Inspirado en los trazados mixtos de pruebas de velocidad de fabricantes como Nardò y Tsukuba.",
        "driving_tips": "La configuración aerodinámica debe ser mínima para volar en las rectas. En la curva 2 en subida que pasa por debajo del puente, mantén la trazada pegada al muro interior para acortar metros de recorrido.",
        "curiosities": [
            "Fue el primer circuito que muchos jugadores disputaron en la demo de Gran Turismo 1 en 1997.",
            "En GT6 permite alcanzar más de 450 km/h en rebufo con el Red Bull X2014 Fan Car.",
            "El puente que cruza la pista está decorado con pantallas LED publicitarias dinámicas."
        ]
    },
    {
        "name": "Apricot Hill Raceway",
        "slug": "apricot-hill",
        "category": "Original",
        "country": "Original",
        "country_code": "gran_turismo",
        "location": "Valle Suave Ficticio",
        "length_km": 3.86,
        "turns": 14,
        "elevation_m": 26.5,
        "longest_straight_m": 530.0,
        "layouts_count": 2,
        "time_progression": 1,
        "weather_change": 1,
        "laser_scanned": 0,
        "first_game": "Gran Turismo 2 (1999)",
        "record_lap": "1:18.230 (Toyota GT-One TS020)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/a/ac/Apricot_Hill_Raceway.jpg/revision/latest/scale-to-width-down/600?cb=20161230125456",
        "svg_path": "assets/tracks/apricot_hill.svg",
        "history_gt": "Uno de los regresos más celebrados en Gran Turismo 6 tras su ausencia en entregas previas. Apricot Hill fue completamente reconstruido desde cero con ciclo día/noche y clima dinámico de lluvia, mostrando atardeceres dorados y charcos reflejando las luces de los boxes.",
        "history_real": "Diseñado como un circuito estilo Gran Premio moderno con amplias escapatorias de grava y pianos bajos estilo FIA.",
        "driving_tips": "La chicana final antes de la recta de meta es muy rápida y se aborda en cuarta marcha: si tocas el bordillo con demasiada violencia catapultarás el coche hacia el muro exterior de boxes.",
        "curiosities": [
            "Debutó en Gran Turismo 2 en 1999 y fue uno de los trazados oficiales de las carreras de resistencia de 200 millas.",
            "Su trazado recuerda en varios sectores técnicos al circuito de Suzuka y al Paul Ricard francés.",
            "En GT6 cuenta con público animado 3D en las gradas y norias iluminadas al anochecer."
        ]
    },
    {
        "name": "Autumn Ring",
        "slug": "autumn-ring",
        "category": "Original",
        "country": "Original",
        "country_code": "gran_turismo",
        "location": "Bosque de Otoño Ficticio",
        "length_km": 2.95,
        "turns": 17,
        "elevation_m": 30.0,
        "longest_straight_m": 425.0,
        "layouts_count": 4,
        "time_progression": 0,
        "weather_change": 0,
        "laser_scanned": 0,
        "first_game": "Gran Turismo 1 (1997)",
        "record_lap": "1:12.300 (Mitsubishi Lancer Evolution VI)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/b/b3/Autumn_Ring.jpg/revision/latest?cb=20161217052219",
        "svg_path": "assets/tracks/autumn_ring.svg",
        "history_gt": "Famoso por su inconfundible ambientación de otoño japonés, con hojas rojizas de arce cayendo sobre el asfalto. Su diseño en forma de 8 con un puente que cruza sobre sí mismo ofrece tanto el trazado principal como el circuito corto 'Autumn Ring Mini'.",
        "history_real": "Evoca las rutas de otoño de las montañas de Hakone y Nikko en Japón.",
        "driving_tips": "El paso por el puente elevado conecta con una horquilla ciega en bajada: frena antes del cambio de rasante para evitar que el ABS alargue la frenada en el aire.",
        "curiosities": [
            "La variante 'Mini' mide apenas 1,281 metros y es el escenario predilecto para batallas de karts y compactos deportivos.",
            "Las hojas otoñales en GT6 reaccionan físicamente al paso de los coches levantándose con el flujo aerodinámico.",
            "Ha estado presente en casi todas las entregas principales de la franquicia desde 1997."
        ]
    },
    {
        "name": "Mid-Field Raceway",
        "slug": "mid-field-raceway",
        "category": "Original",
        "country": "Original",
        "country_code": "gran_turismo",
        "location": "Complejo Montañoso Ficticio",
        "length_km": 3.56,
        "turns": 10,
        "elevation_m": 53.8,
        "longest_straight_m": 940.0,
        "layouts_count": 2,
        "time_progression": 1,
        "weather_change": 1,
        "laser_scanned": 0,
        "first_game": "Gran Turismo 2 (1999)",
        "record_lap": "1:08.450 (Toyota 7 Race Car)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/4/4c/Mid_Field_GT4_Map.png/revision/latest/scale-to-width-down/600?cb=20211025030303",
        "svg_path": "assets/tracks/midfield.svg",
        "history_gt": "Añadido triunfalmente en la actualización 1.16 de GT6 en febrero de 2015. El clásico de GT2 y GT4 regresó con gráficos de nueva generación, ciclo día/noche, clima variable y el espectacular paso del túnel iluminado con neones que cruza por debajo de la recta de meta.",
        "history_real": "Uno de los circuitos de velocidad pura más icónicos de Polyphony Digital, con trazado en 8 y desniveles pronunciados.",
        "driving_tips": "En la primera chicane en subida puedes morder los bordillos agresivamente para mantener la inercia hacia la recta trasera. En el curvón rápido en bajada dentro del túnel mantén la trazada limpia sin sobreviraje.",
        "curiosities": [
            "Fue una de las actualizaciones gratuitas más aclamadas de la historia de Gran Turismo 6.",
            "El trazado en forma de 8 cruza la pista mediante un túnel subterráneo y un puente panorámico.",
            "En condiciones de lluvia nocturna, los reflejos en el asfalto del túnel lucen un acabado fotorrealista sobresaliente en PS3."
        ]
    },
    {
        "name": "Cape Ring",
        "slug": "cape-ring",
        "category": "Original",
        "country": "Original",
        "country_code": "gran_turismo",
        "location": "Isla Costera Ficticia",
        "length_km": 7.03,
        "turns": 24,
        "elevation_m": 68.2,
        "longest_straight_m": 850.0,
        "layouts_count": 5,
        "time_progression": 0,
        "weather_change": 0,
        "laser_scanned": 0,
        "first_game": "Gran Turismo 5",
        "record_lap": "2:10.500 (Pagani Zonda R)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/e/e4/Cape_Ring.jpg/revision/latest/scale-to-width-down/600?cb=20160214165252",
        "svg_path": "assets/tracks/cape_ring.svg",
        "history_gt": "Diseñado para Gran Turismo 5 y perfeccionado en GT6. Es famoso por su característico bucle / rizo de 360 grados en espiral sobre el agua y el salto ciego en el puente donde los coches se despegan del suelo a más de 200 km/h. Ofrece 5 variantes: Full, North, South, Inside y Periphery.",
        "history_real": "Un tributo de Polyphony Digital a los paisajes costeros mediterráneos y a las pruebas de habilidad de alta precisión.",
        "driving_tips": "En el bucle de 360 grados mantén un ángulo de dirección constante y gestiona el gas para no sobrecalentar el neumático exterior. En el salto de la cima alinea las ruedas rectas antes del despegue.",
        "curiosities": [
            "El bucle en espiral de 360 grados no existe en ningún circuito real del mundo por motivos de seguridad.",
            "Con sus 5 variantes, es uno de los complejos modulares más extensos de la saga.",
            "En el puente central los coches sufren compresiones de suspensión extremas."
        ]
    },
    {
        "name": "Gran Turismo Arena",
        "slug": "gt-arena",
        "category": "Original",
        "country": "Original",
        "country_code": "gran_turismo",
        "location": "Estadio Cubierto Multifuncional",
        "length_km": 0.67,
        "turns": 8,
        "elevation_m": 0.0,
        "longest_straight_m": 120.0,
        "layouts_count": 2,
        "time_progression": 0,
        "weather_change": 0,
        "laser_scanned": 0,
        "first_game": "Gran Turismo 6",
        "record_lap": "25.100s (Racing Kart 125 Shifter)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/6/64/ADA79B61-FC3A-4312-9826-B28749C4DD75.png/revision/latest?cb=20190220031508",
        "svg_path": "assets/tracks/gt_arena.svg",
        "history_gt": "Introducido en GT6 como un estadio cubierto de última generación con iluminación teatral y suelo modular. Diseñado para pruebas de habilidad de la 'Coffee Break', gymkhanas de conos, carreras de karts y derrapes de precisión.",
        "history_real": "Inspirado en eventos de arena como la Carrera de Campeones (Race of Champions) celebrada en estadios olímpicos como Wembley y el Nido de Pájaro de Pekín.",
        "driving_tips": "El espacio es sumamente estrecho: usa el freno de mano o golpes de acelerador para rotar el coche en las horquillas cerradas sin tocar los bloques separadores.",
        "curiosities": [
            "Es el circuito cerrado más corto de todo Gran Turismo 6 (668 metros).",
            "La iluminación del estadio cambia dinámicamente con focos de colores según el evento.",
            "Fue la base de las pruebas de slalom de conos de las licencias oficiales de GT6."
        ]
    },

    # ==========================================
    # 3. CIRCUITOS URBANOS (CITY TRACKS)
    # ==========================================
    {
        "name": "Circuito de Madrid",
        "slug": "circuito-de-madrid",
        "category": "Urbano",
        "country": "España",
        "country_code": "espana",
        "location": "Madrid, Comunidad de Madrid",
        "length_km": 3.39,
        "turns": 15,
        "elevation_m": 23.3,
        "longest_straight_m": 420.0,
        "layouts_count": 2,
        "time_progression": 0,
        "weather_change": 0,
        "laser_scanned": 0,
        "first_game": "Gran Turismo 5 / GT6",
        "record_lap": "1:22.350 (Ferrari 458 Italia)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/4/4b/Circuito_de_Madrid.jpg/revision/latest/scale-to-width-down/600?cb=20160205065638",
        "svg_path": "assets/tracks/madrid.svg",
        "history_gt": "Una de las recreaciones urbanas más deslumbrantes de la saga. Polyphony Digital fotografió y modeló con fidelidad milimétrica los monumentos del corazón de Madrid: la Puerta de Alcalá, la Plaza de Cibeles con el Palacio de Telecomunicaciones, la Gran Vía, la Fuente de Neptuno y el Parque del Retiro.",
        "history_real": "Las calles reales del centro neurálgico de la capital de España. Aunque Madrid nunca tuvo un GP urbano en esta zona, el trazado rinde tributo a las carreras callejeras históricas de la Península Ibérica.",
        "driving_tips": "El asfalto urbano tiene menor agarre que un circuito permanente y los bordillos son aceras reales: no montes las ruedas sobre los bordillos de piedra para no dañar la suspensión. En la rotonda de la Puerta de Alcalá mantén el coche colocado en el carril interior para salir traccionando fuerte.",
        "curiosities": [
            "La línea de salida y meta está situada exactamente en la Plaza de la Independencia frente a la Puerta de Alcalá.",
            "En la Plaza de Cibeles se puede apreciar la sede del Ayuntamiento de Madrid con banderas reales ondeando.",
            "Cuenta con una variante corta 'Madrid Mini' de 2,130 metros."
        ]
    },
    {
        "name": "Tokyo R246",
        "slug": "tokyo-r246",
        "category": "Urbano",
        "country": "Japón",
        "country_code": "japon",
        "location": "Aoyama / Shibuya, Tokio",
        "length_km": 5.12,
        "turns": 14,
        "elevation_m": 12.0,
        "longest_straight_m": 880.0,
        "layouts_count": 2,
        "time_progression": 0,
        "weather_change": 0,
        "laser_scanned": 0,
        "first_game": "Gran Turismo 3: A-Spec (2001)",
        "record_lap": "1:31.200 (Honda NSX GT500)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/1/1c/Tokyo_Route_246.jpg/revision/latest/scale-to-width-down/600?cb=20160205035752",
        "svg_path": "assets/tracks/tokyo_r246.svg",
        "history_gt": "El circuito urbano fetiche de Polyphony Digital. Discurre por la Autovía Nacional 246 y el exclusivo bulevar de Aoyama en Shibuya y Minato, a escasos metros de la sede central de Polyphony Digital y las oficinas de Sony Interactive Entertainment en Tokio.",
        "history_real": "Las avenidas reales más glamurosas de Tokio, pasando junto a las boutiques de moda de Omotesando, los jardines del Palacio de Akasaka y la sede de Honda Motor.",
        "driving_tips": "La recta de meta es muy ancha, pero desemboca en una curva de 90 grados a derechas donde se frena a más de 270 km/h: frena en línea recta sobre las marcas viales. En el sector rápido de Akasaka mantén la trazada pegada a los guardarraíles.",
        "curiosities": [
            "El edificio de la sede central corporativa de Honda en Aoyama es perfectamente visible en la curva 1.",
            "Ha sido uno de los circuitos más icónicos de toda la saga desde su presentación en GT3 en 2001.",
            "En GT6 el asfalto refleja el follaje de los 'Ginkgo biloba' de la avenida Meiji Jingu Gaien."
        ]
    },
    {
        "name": "Circuito di Roma",
        "slug": "roma",
        "category": "Urbano",
        "country": "Italia",
        "country_code": "italia",
        "location": "Centro Histórico de Roma",
        "length_km": 3.48,
        "turns": 15,
        "elevation_m": 16.0,
        "longest_straight_m": 550.0,
        "layouts_count": 2,
        "time_progression": 0,
        "weather_change": 0,
        "laser_scanned": 0,
        "first_game": "Gran Turismo 2 (1999) / Remodelado GT5/GT6",
        "record_lap": "1:23.100 (Ferrari 430 Scuderia)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/c/c3/Rome_Circuit_%28GT5%29.jpg/revision/latest/scale-to-width-down/588?cb=20160205071730",
        "svg_path": "assets/tracks/roma.svg",
        "history_gt": "Una oda a la Ciudad Eterna. Remodelado para GT5 y optimizado en GT6, el trazado bordea el imponente Coliseo Romano, pasa por los foros imperiales, la Plaza de la República y la Vía Véneto bajo una cálida luz mediterránea.",
        "history_real": "Las calzadas romanas históricas donde compitieron los bólidos en el Gran Premio de Roma entre 1925 y 1954 con leyendas como Tazio Nuvolari y Luigi Villoresi.",
        "driving_tips": "El paso junto al Coliseo tiene una horquilla muy cerrada a izquierdas sobre adoquines pulidos: frena temprano para no irte largo contra las barreras de protección de los monumentos.",
        "curiosities": [
            "En GT2 existía una versión nocturna clásica de Roma que fue completamente rediseñada en la era de PS3.",
            "El detalle arquitectónico de las piedras del Coliseo y las esculturas clásicas fue modelado por artistas italianos.",
            "Tiene una de las rectas de boxes más pintorescas con la arquitectura barroca de Roma como telón de fondo."
        ]
    },
    {
        "name": "Côte d'Azur (Montecarlo)",
        "slug": "cote-d-azur",
        "category": "Urbano",
        "country": "Mónaco",
        "country_code": "monaco",
        "location": "Montecarlo / La Condamine",
        "length_km": 3.34,
        "turns": 19,
        "elevation_m": 42.0,
        "longest_straight_m": 510.0,
        "layouts_count": 1,
        "time_progression": 0,
        "weather_change": 0,
        "laser_scanned": 0,
        "first_game": "Gran Turismo 3: A-Spec (2001)",
        "record_lap": "1:12.909 (Lewis Hamilton, Mercedes W10, 2019)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/2/2b/Cote_d%27Azur.jpg/revision/latest/scale-to-width-down/600?cb=20160120111339",
        "svg_path": "assets/tracks/cote_dazur.svg",
        "history_gt": "La réplica exacta del trazado del Gran Premio de Mónaco de Fórmula 1, denominada 'Côte d'Azur' en la saga por motivos de derechos de marca. Reproduce cada milímetro del circuito callejero más glamuroso del mundo: Santa Devota, la subida a Beau Rivage, la plaza del Casino, Mirabeau, la horquilla Loews/Fairmont, el túnel y la Rascasse.",
        "history_real": "Inaugurado en 1929, el Gran Premio de Mónaco es la joya de la corona del automovilismo mundial. Nelson Piquet lo definió célebremente como 'pilotar una bicicleta en el salón de tu casa'. Ayrton Senna tiene el récord absoluto de 6 victorias en estas calles.",
        "driving_tips": "En Mónaco no hay margen de error: un milímetro de desvío significa chocar contra el guardarraíl de acero armco. En la horquilla Fairmont (la curva más lenta de la F1 a 45 km/h) gira el volante con el radio máximo y ajusta el bloqueo de dirección en el garaje.",
        "curiosities": [
            "En el túnel con vistas al puerto deportivo se experimenta una transición visual de oscuridad a luz deslumbrante al salir a la chicane del puerto.",
            "Los yates atracados en la bahía de Montecarlo y el Hotel de Paris están modelados con gran lujo de detalles en GT6.",
            "Es uno de los circuitos más desafiantes para adelantar sin cometer una penalización en salas online."
        ]
    },
    {
        "name": "London Circuit",
        "slug": "london",
        "category": "Urbano",
        "country": "Reino Unido",
        "country_code": "uk",
        "location": "Westminster, Londres",
        "length_km": 1.92,
        "turns": 9,
        "elevation_m": 4.5,
        "longest_straight_m": 380.0,
        "layouts_count": 2,
        "time_progression": 0,
        "weather_change": 0,
        "laser_scanned": 0,
        "first_game": "Gran Turismo 5 Prologue (2007)",
        "record_lap": "55.400s (Aston Martin V12 Vantage)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/f/f6/London.jpg/revision/latest/scale-to-width-down/497?cb=20160205054442",
        "svg_path": "assets/tracks/london.svg",
        "history_gt": "Presentado en GT5 Prologue y optimizado en GT6. Transcurre por el corazón monumental del Londres histórico: rodea Trafalgar Square con la Columna de Nelson, desciende por Whitehall pasando junto a Downing Street y atraviesa el monumental arco del Almirantazgo hacia The Mall.",
        "history_real": "Las calles neurálgicas del gobierno británico en Westminster, reconocibles por las icónicas cabinas de teléfono rojas y los autobuses de dos pisos 'Routemaster'.",
        "driving_tips": "El trazado es corto y muy ratonero con esquinas de 90 grados: usa una relación de marchas corta y un diferencial autoblocante tarado con aceleración reactiva para salir sin subviraje de las curvas lentas.",
        "curiosities": [
            "El Big Ben y las Casas del Parlamento son visibles en la lejanía al final de la recta de Whitehall.",
            "Al pasar por Trafalgar Square se aprecian las esculturas de los cuatro leones de bronce en la base de la columna.",
            "Es un circuito ideal para carreras de turismos británicos clásicos como el Mini Cooper y Jaguar E-Type."
        ]
    },
    {
        "name": "Special Stage Route 5",
        "slug": "ssr5",
        "category": "Urbano",
        "country": "Japón",
        "country_code": "japon",
        "location": "Shuto Expressway, Tokio",
        "length_km": 3.79,
        "turns": 14,
        "elevation_m": 21.0,
        "longest_straight_m": 720.0,
        "layouts_count": 3,
        "time_progression": 0,
        "weather_change": 1,
        "laser_scanned": 0,
        "first_game": "Gran Turismo 1 (1997)",
        "record_lap": "1:18.900 (Nissan GT-R Nismo GT3)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/9/96/Special_Stage_Route_5_Map.png/revision/latest/scale-to-width-down/600?cb=20211023233009",
        "svg_path": "assets/tracks/ssr5.svg",
        "history_gt": "La quintaesencia de las carreras nocturnas callejeras de Tokio en la saga Gran Turismo. Inspirado en la famosa red de autopistas elevadas Shuto Expressway ('Wangan') bajo las luces de neón de los rascacielos. En GT6 cuenta con asfalto mojado bajo lluvia nocturna con reflejos brillantes y la variante 'Clubman Stage Route 5'.",
        "history_real": "Rinde homenaje a la cultura 'Mid Night Club' de los años 80 y 90, donde deportivos modificados japoneses corrían a más de 300 km/h por las autopistas de peaje de la bahía de Tokio.",
        "driving_tips": "La chicane ciega a mitad de circuito exige saltar sobre los bordillos con el coche perfectamente colocado. En el trazado bajo lluvia el asfalto mojado reduce la tracción a la salida de las curvas de 90 grados.",
        "curiosities": [
            "Ha estado presente en casi todas las generaciones de Gran Turismo desde la PlayStation original.",
            "La variante 'Clubman Stage Route 5' mide solo 2,466 m y es un circuito corto ultra-intenso para coches compactos.",
            "Los túneles de hormigón cuentan con ventiladores gigantescos y carteles luminosos en kanji y katakana."
        ]
    },
    {
        "name": "Special Stage Route 7",
        "slug": "ssr7",
        "category": "Urbano",
        "country": "Japón",
        "country_code": "japon",
        "location": "Bahía de Tokio",
        "length_km": 23.29,
        "turns": 20,
        "elevation_m": 80.0,
        "longest_straight_m": 7100.0,
        "layouts_count": 1,
        "time_progression": 0,
        "weather_change": 1,
        "laser_scanned": 0,
        "first_game": "Gran Turismo 5 / GT6",
        "record_lap": "5:32.400 (Red Bull X2014 Fan Car)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/d/db/Special_Stage_Route_7.jpg/revision/latest/scale-to-width-down/600?cb=20160119153223",
        "svg_path": "assets/tracks/ssr7.svg",
        "history_gt": "Una autopista costera colosal de más de 23 kilómetros sumergida en la noche y azotada por la lluvia. Su característica más asombrosa es una recta subterránea dentro de un túnel que se prolonga durante más de 7 kilómetros seguidos, convirtiéndose en el banco de pruebas oficial para medir la velocidad máxima absoluta de cualquier vehículo en GT6.",
        "history_real": "Inspirada en la 'Tokyo Bay Aqua-Line', la colosal autovía-túnel que cruza la bahía de Tokio entre Kawasaki y Kisarazu sobre el mar.",
        "driving_tips": "Configura la caja de cambios con la relación más larga posible para no tocar el corte de inyección en la recta de 7 km. La lluvia torrencial puede provocar 'aquaplaning' a velocidades superiores a 350 km/h: mantén las dos manos firmes sin hacer movimientos bruscos de volante.",
        "curiosities": [
            "Su recta de 7.1 km es la recta pavimentada continua más larga de cualquier circuito en la historia de los videojuegos.",
            "Los puentes colgantes sobre el mar reproducen fielmente el Rainbow Bridge de la bahía de Tokio con fuegos artificiales al fondo.",
            "En las salas online de GT6 era el circuito más popular para competiciones de 'Top Speed' y carreras de aceleración 'Roll Racing'."
        ]
    },
    {
        "name": "Special Stage Route X",
        "slug": "ssrx",
        "category": "Urbano",
        "country": "Estados Unidos",
        "country_code": "usa",
        "location": "Costa del Pacífico Ficticia",
        "length_km": 30.28,
        "turns": 2,
        "elevation_m": 65.0,
        "longest_straight_m": 12000.0,
        "layouts_count": 1,
        "time_progression": 1,
        "weather_change": 1,
        "laser_scanned": 0,
        "first_game": "Gran Turismo 5 (DLC) / GT6",
        "record_lap": "3:10.200 (Red Bull X2014 Fan Car, >500 km/h)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/6/6d/Special_Stage_Route_X.jpg/revision/latest?cb=20160119155327",
        "svg_path": "assets/tracks/ssrx.svg",
        "history_gt": "El óvalo de alta velocidad definitivo. Con 30.28 kilómetros de longitud total y dos rectas gemelas de 12 kilómetros cada una conectadas por dos curvas peraltadas monumentales a 35 grados sobre el océano. Diseñado específicamente para pruebas aerodinámicas, aceleración de 0 a 400 km/h y análisis de telemetría de par motor.",
        "history_real": "Inspirado en los centros de pruebas de velocidad ultra-secreta de fabricantes como el óvalo de Ehra-Lessien de Volkswagen en Alemania y el circuito de Nardò en Italia.",
        "driving_tips": "El rebufo aquí es descomunal: colócate a rebufo de un coche rival para romper la barrera de los 480-500 km/h. La entrada a los dos peraltes inclinados se realiza a velocidad máxima sin soltar el acelerador.",
        "curiosities": [
            "Con 30.3 km de perímetro, es el trazado de mayor longitud absoluta de todo Gran Turismo 6.",
            "En las rectas de 12 km se aprecia la curvatura de la Tierra en el horizonte gráfico del juego.",
            "Fue el escenario oficial del 'Speed Test Pack' para medir tiempos de aceleración en 400m, 1,000m y velocidad punta."
        ]
    },

    # ==========================================
    # 4. MONTAÑA, TIERRA, NIEVE Y ESPECIALES
    # ==========================================
    {
        "name": "Eiger Nordwand",
        "slug": "eiger-nordwand",
        "category": "Tierra y Nieve",
        "country": "Suiza",
        "country_code": "suiza",
        "location": "Kleine Scheidegg, Cantón de Berna",
        "length_km": 2.44,
        "turns": 11,
        "elevation_m": 82.0,
        "longest_straight_m": 250.0,
        "layouts_count": 4,
        "time_progression": 0,
        "weather_change": 0,
        "laser_scanned": 0,
        "first_game": "Gran Turismo HD Concept (2006) / GT5 / GT6",
        "record_lap": "1:05.800 (Ferrari 599)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/a/a2/Eiger_Nordwand-0.png/revision/latest?cb=20171026075848",
        "svg_path": "assets/tracks/eiger.svg",
        "history_gt": "Eiger Nordwand fue el circuito embajador de la llegada de Gran Turismo a la alta definición en PlayStation 3 con 'Gran Turismo HD Concept' en 2006. En GT6 cuenta tanto con el trazado corto y largo de asfalto como con los brutales tramos de tierra y grava 'K Trail' y 'G Trail' con saltos entre paredes de roca viva.",
        "history_real": "Ubicado a los pies de la mítica cara norte del monte Eiger (3,967 m), la pared rocosa más temida y legendaria de la historia del alpinismo europeo.",
        "driving_tips": "En los trazados de grava (Dirt), activa la tracción total y anticipa la frenada colocando el coche de lado ('flick escandinavo') antes de llegar a la horquilla para que la gravedad y los neumáticos de tacos te empujen hacia el interior de la curva.",
        "curiosities": [
            "El tren cremallera rojo del Jungfraubahn cruza por un puente superior mientras compites en la pista.",
            "Tiene un desnivel vertical de más de 80 metros en apenas 2.4 kilómetros de recorrido.",
            "Fue el primer circuito en 1080p nativo que el mundo pudo jugar en la era de PS3."
        ]
    },
    {
        "name": "Toscana",
        "slug": "toscana",
        "category": "Tierra y Nieve",
        "country": "Italia",
        "country_code": "italia",
        "location": "Val d'Orcia, Toscana",
        "length_km": 3.41,
        "turns": 16,
        "elevation_m": 48.0,
        "longest_straight_m": 380.0,
        "layouts_count": 2,
        "time_progression": 1,
        "weather_change": 0,
        "laser_scanned": 0,
        "first_game": "Gran Turismo 5 / GT6",
        "record_lap": "1:42.100 (Lancia Delta HF Integrale Rally)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/0/0c/Toscana.jpg/revision/latest/scale-to-width-down/600?cb=20160120145929",
        "svg_path": "assets/tracks/toscana.svg",
        "history_gt": "Una de las postales más bellas de Gran Turismo. Ambientado en las ondulantes colinas toscanas de cipreses centenarios, viñedos y granjas de piedra durante la puesta de sol. Cuenta con trazado de grava compacta con polvo volumétrico iluminado por los faros en carreras nocturnas y versión de asfalto.",
        "history_real": "Inspirado en los tramos de tierra del Rally de San Remo y las carreteras blancas de grava ('Strade Bianche') de la campiña italiana.",
        "driving_tips": "En la grava seca de Toscana el coche baila sobre las crestas: ajusta un diferencial con precarga baja para permitir que el tren trasero deslice con progresividad controlada sin cruzarse en exceso.",
        "curiosities": [
            "La iluminación dorada de atardecer toscano fue premiada como uno de los mayores logros artísticos en PS3.",
            "Incluye polvo dinámico volumétrico que se queda suspendido en el aire cegando a los coches que vienen detrás.",
            "Cuenta con trazado de tierra y trazado de asfalto en sentido normal e inverso."
        ]
    },
    {
        "name": "Chamonix",
        "slug": "chamonix",
        "category": "Tierra y Nieve",
        "country": "Francia",
        "country_code": "francia",
        "location": "Chamonix-Mont-Blanc, Alta Saboya",
        "length_km": 3.20,
        "turns": 14,
        "elevation_m": 60.0,
        "longest_straight_m": 310.0,
        "layouts_count": 4,
        "time_progression": 1,
        "weather_change": 1,
        "laser_scanned": 0,
        "first_game": "Gran Turismo 4",
        "record_lap": "1:45.300 (Peugeot 205 Turbo 16 Evolution 2)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/5/5b/Chamonix_%28GT4%29.jpg/revision/latest?cb=20160117041159",
        "svg_path": "assets/tracks/chamonix.svg",
        "history_gt": "El reino del hielo y la nieve en Gran Turismo. Situado a los pies del imponente Mont Blanc en los Alpes franceses. En GT6 ofrece cuatro variantes (Main, East, West y Mini) con bancos de nieve acumulada en los laterales, placas de hielo vivo y ventiscas de nieve dinámicas con ciclo nocturno.",
        "history_real": "Hogar de las famosas carreras sobre hielo de las 24 Horas de Chamonix y del legendario Trofeo Andros francés donde compiten campeones como Alain Prost y Sébastien Loeb.",
        "driving_tips": "Obligatorio equipar neumáticos de nieve con clavos (Spikes). En el hielo el agarre es mínimo: la clave es iniciar el giro mucho antes de la curva y usar la inercia del coche apoyando suavemente la rueda trasera exterior contra los bancos de nieve blandos para encarrilar la salida.",
        "curiosities": [
            "Las partículas de nieve desprendidas por los cuatro neumáticos de clavos forman estelas blancas que reducen la visibilidad del parabrisas.",
            "Fue el circuito oficial para las pruebas de tracción total con vehículos del Grupo B como el Audi Sport quattro S1.",
            "En la variante nocturna, las luces de los chalets de montaña y las estaciones de esquí brillan en la penumbra alpina."
        ]
    },
    {
        "name": "Gran Turismo Kart Raceway / Kart Space",
        "slug": "kart-space",
        "category": "Especial",
        "country": "Original",
        "country_code": "gran_turismo",
        "location": "Recinto Indoor Futurista",
        "length_km": 0.82,
        "turns": 11,
        "elevation_m": 2.0,
        "longest_straight_m": 160.0,
        "layouts_count": 3,
        "time_progression": 0,
        "weather_change": 0,
        "laser_scanned": 0,
        "first_game": "Gran Turismo 5 / GT6",
        "record_lap": "32.150s (Gran Turismo Racing Kart 125)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/6/64/ADA79B61-FC3A-4312-9826-B28749C4DD75.png/revision/latest?cb=20190220031508",
        "svg_path": "assets/tracks/kart_space.svg",
        "history_gt": "Los circuitos especializados de karts en GT6. 'Kart Space I & II' ofrecen un trazado indoor futurista con túneles iluminados por luces de neón estilo 'Tron' y asfalto pulido de altísima adherencia, mientras que 'Gran Turismo Kart Raceway' es un circuito al aire libre de competición homologado según normativas CIK-FIA.",
        "history_real": "El karting es la cuna obligatoria donde todos los campeones de Fórmula 1 (Senna, Hamilton, Alonso, Verstappen) aprendieron los fundamentos del pilotaje a flor de asfalto.",
        "driving_tips": "En los karts no hay diferencial ni suspensión: tu cuerpo y la inclinación del chasis tubular determinan la tracción. Sé muy suave con la dirección para no frenar el eje trasero rígido.",
        "curiosities": [
            "La sensación de velocidad a 120 km/h en un kart de 125cc con el trasero a 3 cm del suelo es una de las experiencias físicas más puras del juego.",
            "Kart Space cuenta con luces estroboscópicas y reflejos psicodélicos en las paredes de metacrilato.",
            "Permite competir con karts infantiles de 100cc, karts de 125cc estándar y los potentes karts de marchas Shifter de 6 velocidades."
        ]
    },
    {
        "name": "Exploración Lunar (Misión Apolo 15)",
        "slug": "lunar-exploration",
        "category": "Especial",
        "country": "La Luna",
        "country_code": "moon",
        "location": "Rima Hadley, Montes Apenninus, La Luna",
        "length_km": 5.20,
        "turns": 18,
        "elevation_m": 120.0,
        "longest_straight_m": 450.0,
        "layouts_count": 3,
        "time_progression": 0,
        "weather_change": 0,
        "laser_scanned": 1,
        "first_game": "Gran Turismo 6",
        "record_lap": "1:35.800 (Lunar Roving Vehicle LRV-001 '71)",
        "image_url": "https://static.wikia.nocookie.net/gran-turismo/images/1/1a/Lunar_Roving_Vehicle_LRV-001_%2771.jpg/revision/latest/scale-to-width-down/600?cb=20160204081128",
        "svg_path": "assets/tracks/lunar.svg",
        "history_gt": "La proeza científica y técnica más insólita de la historia de los videojuegos de conducción. Polyphony Digital colaboró con científicos de la NASA y utilizó datos cartográficos topográficos y altimétricos reales de satélite de la cuenca lunar de Hadley Rille para recrear la superficie lunar con 1/6 de la gravedad terrestre (1.62 m/s²). Los jugadores pilotan el vehículo lunar oficial 'Lunar Roving Vehicle LRV-001' de la misión Apolo 15 bajo el cielo negro espacial con la Tierra visible en el firmamento.",
        "history_real": "El 31 de julio de 1971, los astronautas David Scott y James Irwin de la misión Apolo 15 de la NASA se convirtieron en los primeros seres humanos en conducir un vehículo motorizado en un cuerpo celeste fuera de la Tierra, recorriendo 27.7 kilómetros por la superficie lunar explorando cráteres y el cañón de la Rima Hadley.",
        "driving_tips": "A 1/6 de la gravedad terrestre, cualquier bache o cambio de rasante a más de 15 km/h hará que el rover lunar vuele durante segundos flotando en el vacío. Frena con mucha anticipación porque sin fricción atmosférica ni peso suficiente el neumático de malla metálica tarda cuatro veces más en detener el vehículo.",
        "curiosities": [
            "Las estrellas y constelaciones visibles desde la Luna en GT6 están calculadas con exactitud astronómica según la posición del cielo en julio de 1971.",
            "El Lunar Roving Vehicle cuenta con cuatro motores eléctricos independientes de 0.25 CV en cada rueda y tracción a las 4 ruedas.",
            "En el horizonte lunar se pueden observar los restos del módulo lunar 'Falcon' y la bandera de los Estados Unidos plantada en el regolito."
        ]
    }
]

def main():
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    print(f"Iniciando inserción y actualización de {len(TRACKS_DATA)} circuitos en database/gt_academy.db...")

    inserted = 0
    updated = 0

    for t in TRACKS_DATA:
        curiosities_json = json.dumps(t.get('curiosities', []), ensure_ascii=False)
        
        cursor.execute("""
            INSERT INTO tracks (
                name, slug, category, country, country_code, location,
                length_km, turns, elevation_m, longest_straight_m, layouts_count,
                time_progression, weather_change, laser_scanned, first_game,
                record_lap, image_url, svg_path, history_gt, history_real,
                driving_tips, curiosities
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(slug) DO UPDATE SET
                name = excluded.name,
                category = excluded.category,
                country = excluded.country,
                country_code = excluded.country_code,
                location = excluded.location,
                length_km = excluded.length_km,
                turns = excluded.turns,
                elevation_m = excluded.elevation_m,
                longest_straight_m = excluded.longest_straight_m,
                layouts_count = excluded.layouts_count,
                time_progression = excluded.time_progression,
                weather_change = excluded.weather_change,
                laser_scanned = excluded.laser_scanned,
                first_game = excluded.first_game,
                record_lap = excluded.record_lap,
                image_url = excluded.image_url,
                svg_path = excluded.svg_path,
                history_gt = excluded.history_gt,
                history_real = excluded.history_real,
                driving_tips = excluded.driving_tips,
                curiosities = excluded.curiosities
        """, (
            t['name'], t['slug'], t['category'], t['country'], t['country_code'], t['location'],
            t['length_km'], t['turns'], t['elevation_m'], t['longest_straight_m'], t['layouts_count'],
            t['time_progression'], t['weather_change'], t['laser_scanned'], t['first_game'],
            t.get('record_lap', ''), t.get('image_url', ''), t.get('svg_path', ''),
            t['history_gt'], t['history_real'], t['driving_tips'], curiosities_json
        ))
        if cursor.rowcount > 0:
            inserted += 1

    conn.commit()
    conn.close()

    print(f"Completado con éxito: {inserted} circuitos registrados en la base de datos.")

if __name__ == '__main__':
    main()
